name: Smoke Tests - PR
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Install Java 20
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '20.0.2'
          cache: 'maven'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Chrome Driver
        uses: actions/checkout@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional  

      - name: Run tests
        run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-headless